language: go
os: linux
dist: focal
go:
  - 1.16.x
script:
  - make lint
  - make goreleaser-build
  - make test
  - make testacc
deploy:
  - provider: script
    script: make goreleaser-release
    on:
#      tags: true
      branch: wojciech-goreleaser
